/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VideoConsultRouteImport } from './routes/video-consult'
import { Route as ResidencesRouteImport } from './routes/residences'
import { Route as RequestRouteImport } from './routes/request'
import { Route as MemoryCareRouteImport } from './routes/memory-care'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CaregiversRouteImport } from './routes/caregivers'
import { Route as CareSuggestRouteImport } from './routes/care-suggest'
import { Route as CareHomesRouteImport } from './routes/care-homes'
import { Route as CareAtHomeRouteImport } from './routes/care-at-home'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ResidencesIndexRouteImport } from './routes/residences.index'
import { Route as CareAtHomeIndexRouteImport } from './routes/care-at-home.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'
import { Route as ResidencesSlugRouteImport } from './routes/residences.$slug'
import { Route as CareAtHomeSlugRouteImport } from './routes/care-at-home.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'

const VideoConsultRoute = VideoConsultRouteImport.update({
  id: '/video-consult',
  path: '/video-consult',
  getParentRoute: () => rootRouteImport,
} as any)
const ResidencesRoute = ResidencesRouteImport.update({
  id: '/residences',
  path: '/residences',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestRoute = RequestRouteImport.update({
  id: '/request',
  path: '/request',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoryCareRoute = MemoryCareRouteImport.update({
  id: '/memory-care',
  path: '/memory-care',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CaregiversRoute = CaregiversRouteImport.update({
  id: '/caregivers',
  path: '/caregivers',
  getParentRoute: () => rootRouteImport,
} as any)
const CareSuggestRoute = CareSuggestRouteImport.update({
  id: '/care-suggest',
  path: '/care-suggest',
  getParentRoute: () => rootRouteImport,
} as any)
const CareHomesRoute = CareHomesRouteImport.update({
  id: '/care-homes',
  path: '/care-homes',
  getParentRoute: () => rootRouteImport,
} as any)
const CareAtHomeRoute = CareAtHomeRouteImport.update({
  id: '/care-at-home',
  path: '/care-at-home',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResidencesIndexRoute = ResidencesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ResidencesRoute,
} as any)
const CareAtHomeIndexRoute = CareAtHomeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CareAtHomeRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ResidencesSlugRoute = ResidencesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ResidencesRoute,
} as any)
const CareAtHomeSlugRoute = CareAtHomeSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CareAtHomeRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/care-at-home': typeof CareAtHomeRouteWithChildren
  '/care-homes': typeof CareHomesRoute
  '/care-suggest': typeof CareSuggestRoute
  '/caregivers': typeof CaregiversRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/memory-care': typeof MemoryCareRoute
  '/request': typeof RequestRoute
  '/residences': typeof ResidencesRouteWithChildren
  '/video-consult': typeof VideoConsultRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/care-at-home/$slug': typeof CareAtHomeSlugRoute
  '/residences/$slug': typeof ResidencesSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/care-at-home/': typeof CareAtHomeIndexRoute
  '/residences/': typeof ResidencesIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/care-homes': typeof CareHomesRoute
  '/care-suggest': typeof CareSuggestRoute
  '/caregivers': typeof CaregiversRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/memory-care': typeof MemoryCareRoute
  '/request': typeof RequestRoute
  '/video-consult': typeof VideoConsultRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/care-at-home/$slug': typeof CareAtHomeSlugRoute
  '/residences/$slug': typeof ResidencesSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/blog': typeof BlogIndexRoute
  '/care-at-home': typeof CareAtHomeIndexRoute
  '/residences': typeof ResidencesIndexRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/care-at-home': typeof CareAtHomeRouteWithChildren
  '/care-homes': typeof CareHomesRoute
  '/care-suggest': typeof CareSuggestRoute
  '/caregivers': typeof CaregiversRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/memory-care': typeof MemoryCareRoute
  '/request': typeof RequestRoute
  '/residences': typeof ResidencesRouteWithChildren
  '/video-consult': typeof VideoConsultRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/care-at-home/$slug': typeof CareAtHomeSlugRoute
  '/residences/$slug': typeof ResidencesSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/care-at-home/': typeof CareAtHomeIndexRoute
  '/residences/': typeof ResidencesIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/care-at-home'
    | '/care-homes'
    | '/care-suggest'
    | '/caregivers'
    | '/contact'
    | '/dashboard'
    | '/faq'
    | '/login'
    | '/memory-care'
    | '/request'
    | '/residences'
    | '/video-consult'
    | '/blog/$slug'
    | '/care-at-home/$slug'
    | '/residences/$slug'
    | '/services/$slug'
    | '/blog/'
    | '/care-at-home/'
    | '/residences/'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/care-homes'
    | '/care-suggest'
    | '/caregivers'
    | '/contact'
    | '/dashboard'
    | '/faq'
    | '/login'
    | '/memory-care'
    | '/request'
    | '/video-consult'
    | '/blog/$slug'
    | '/care-at-home/$slug'
    | '/residences/$slug'
    | '/services/$slug'
    | '/blog'
    | '/care-at-home'
    | '/residences'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/care-at-home'
    | '/care-homes'
    | '/care-suggest'
    | '/caregivers'
    | '/contact'
    | '/dashboard'
    | '/faq'
    | '/login'
    | '/memory-care'
    | '/request'
    | '/residences'
    | '/video-consult'
    | '/blog/$slug'
    | '/care-at-home/$slug'
    | '/residences/$slug'
    | '/services/$slug'
    | '/blog/'
    | '/care-at-home/'
    | '/residences/'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  CareAtHomeRoute: typeof CareAtHomeRouteWithChildren
  CareHomesRoute: typeof CareHomesRoute
  CareSuggestRoute: typeof CareSuggestRoute
  CaregiversRoute: typeof CaregiversRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  FaqRoute: typeof FaqRoute
  LoginRoute: typeof LoginRoute
  MemoryCareRoute: typeof MemoryCareRoute
  RequestRoute: typeof RequestRoute
  ResidencesRoute: typeof ResidencesRouteWithChildren
  VideoConsultRoute: typeof VideoConsultRoute
  BlogSlugRoute: typeof BlogSlugRoute
  ServicesSlugRoute: typeof ServicesSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/video-consult': {
      id: '/video-consult'
      path: '/video-consult'
      fullPath: '/video-consult'
      preLoaderRoute: typeof VideoConsultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/residences': {
      id: '/residences'
      path: '/residences'
      fullPath: '/residences'
      preLoaderRoute: typeof ResidencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request': {
      id: '/request'
      path: '/request'
      fullPath: '/request'
      preLoaderRoute: typeof RequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memory-care': {
      id: '/memory-care'
      path: '/memory-care'
      fullPath: '/memory-care'
      preLoaderRoute: typeof MemoryCareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/caregivers': {
      id: '/caregivers'
      path: '/caregivers'
      fullPath: '/caregivers'
      preLoaderRoute: typeof CaregiversRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/care-suggest': {
      id: '/care-suggest'
      path: '/care-suggest'
      fullPath: '/care-suggest'
      preLoaderRoute: typeof CareSuggestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/care-homes': {
      id: '/care-homes'
      path: '/care-homes'
      fullPath: '/care-homes'
      preLoaderRoute: typeof CareHomesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/care-at-home': {
      id: '/care-at-home'
      path: '/care-at-home'
      fullPath: '/care-at-home'
      preLoaderRoute: typeof CareAtHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/residences/': {
      id: '/residences/'
      path: '/'
      fullPath: '/residences/'
      preLoaderRoute: typeof ResidencesIndexRouteImport
      parentRoute: typeof ResidencesRoute
    }
    '/care-at-home/': {
      id: '/care-at-home/'
      path: '/'
      fullPath: '/care-at-home/'
      preLoaderRoute: typeof CareAtHomeIndexRouteImport
      parentRoute: typeof CareAtHomeRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/residences/$slug': {
      id: '/residences/$slug'
      path: '/$slug'
      fullPath: '/residences/$slug'
      preLoaderRoute: typeof ResidencesSlugRouteImport
      parentRoute: typeof ResidencesRoute
    }
    '/care-at-home/$slug': {
      id: '/care-at-home/$slug'
      path: '/$slug'
      fullPath: '/care-at-home/$slug'
      preLoaderRoute: typeof CareAtHomeSlugRouteImport
      parentRoute: typeof CareAtHomeRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CareAtHomeRouteChildren {
  CareAtHomeSlugRoute: typeof CareAtHomeSlugRoute
  CareAtHomeIndexRoute: typeof CareAtHomeIndexRoute
}

const CareAtHomeRouteChildren: CareAtHomeRouteChildren = {
  CareAtHomeSlugRoute: CareAtHomeSlugRoute,
  CareAtHomeIndexRoute: CareAtHomeIndexRoute,
}

const CareAtHomeRouteWithChildren = CareAtHomeRoute._addFileChildren(
  CareAtHomeRouteChildren,
)

interface ResidencesRouteChildren {
  ResidencesSlugRoute: typeof ResidencesSlugRoute
  ResidencesIndexRoute: typeof ResidencesIndexRoute
}

const ResidencesRouteChildren: ResidencesRouteChildren = {
  ResidencesSlugRoute: ResidencesSlugRoute,
  ResidencesIndexRoute: ResidencesIndexRoute,
}

const ResidencesRouteWithChildren = ResidencesRoute._addFileChildren(
  ResidencesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  CareAtHomeRoute: CareAtHomeRouteWithChildren,
  CareHomesRoute: CareHomesRoute,
  CareSuggestRoute: CareSuggestRoute,
  CaregiversRoute: CaregiversRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  FaqRoute: FaqRoute,
  LoginRoute: LoginRoute,
  MemoryCareRoute: MemoryCareRoute,
  RequestRoute: RequestRoute,
  ResidencesRoute: ResidencesRouteWithChildren,
  VideoConsultRoute: VideoConsultRoute,
  BlogSlugRoute: BlogSlugRoute,
  ServicesSlugRoute: ServicesSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
